DBのモックを削除
Yuya-Furusawa/quest-api pull request #13
Opened 2023-08-02 13:26 UTC by AtsukiTak

- `~RepositoryForMemory` 系の構造体を削除
- 関連するテストの修正

2023-08-02 17:35 UTC, Yuya-Furusawa requested changes
それぞれのテストで、終わりにDBのクリーニング必要よね？？？

2023-08-03 06:16 UTC, AtsukiTak commented
> それぞれのテストで、終わりにDBのクリーニング必要よね？？？

それが終わりにクリーニングすればよいという話でもなくて、テスト失敗したり途中でpanicしたりするとテストコード最後まで走らなくてクリーニングされなくなってしまうので、別途panicをキャッチして、クリーニングして、またpanicを再開させて、という処理が必要になる。いわゆるteardown処理。
ただもうDBもモックから実物に置き換えたので、今みたいにユニットテストで各handlerをテストしていくより、普通にサーバー立ててそこにリクエストを送っていく方式のテスト（インテグレーションテスト）に移行しようかなと思っている。（正常系は特に）
その場合、インテグレーションテストの最初にDB立てて、初期化して、を毎回やることになるのでteardown処理いらなくなるので、一旦今回はteardown処理の実装を見送ろうかなという感じ。

2023-08-04 05:57 UTC, Yuya-Furusawa commented
なるほど、理解した。
確かにpanic処理とかも考えるとテストの負担が大きいか

ちなみにこの場合だと連続してテスト走らせることができないけどそれは大丈夫？（それを気にしてた）
具体的には`should_all_quests`が２回目以降走らせるとコケちゃうので手動でDBをクリーニングする必要があるけど、まあそれはいいのか

2023-08-04 05:59 UTC, Yuya-Furusawa commented
@AtsukiTak 
`should_participate_quest`のテストがミスってたから修正してコミットしました！

2023-08-04 11:18 UTC, AtsukiTak commented
> ちなみにこの場合だと連続してテスト走らせることができないけどそれは大丈夫？（それを気にしてた）
具体的にはshould_all_questsが２回目以降走らせるとコケちゃうので手動でDBをクリーニングする必要があるけど、まあそれはいいのか

実は一旦 `should_all_quests` の後処理を実装したんだけど、他のとこやってないのにこれだけやるのも違うか？？ってなって消した過去がある笑
けどまあちゃんとやったほうがいいか。やります笑

2023-08-04 16:01 UTC, AtsukiTak commented
これ実装してたんだけど、`should_all_quests` テスト以外で作成したクエストも削除しないといけないことに気がついて、さらに実行のタイミングによっては、
1. 他のテストでクエストを作成する
2. `should_all_quests` を実行する
3. 他のテストでクエストを削除する

とかになって失敗することに気がついた。

一旦そこのテスト修正は別PRでやるわ

2023-08-05 06:30 UTC, Yuya-Furusawa approved these changes

2023-08-05 06:31 UTC, Yuya-Furusawa commented
了解です！じゃあ一旦このPRは閉じて、テストの修正は別PRにしよう！

2023-08-05 06:31 UTC, merged